version: "3.3"

# ! security_opt is set for development purposes
services:
  db:
    image: postgres:13-bullseye
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notbank
      - POSTGRES_USER=notbank
      - POSTGRES_PASSWORD=notbank
    security_opt:
      - "apparmor=unconfined"
    ports:
      - "5433:5432"
  redis:
    image: "redis:6.0-bullseye"
    security_opt:
      - "apparmor=unconfined"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    security_opt:
      - "apparmor=unconfined"
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    security_opt:
      - "apparmor=unconfined"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: &python-service python-service
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/home/user/backend
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=notbank
      - POSTGRES_USER=notbank
      - POSTGRES_PASSWORD=notbank
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - db
      - redis
      - broker
    security_opt:
      - "apparmor=unconfined"
  celery:
    image: *python-service
    command: pipenv run celery -A "config.celery.app" worker -l info
    environment:
      - POSTGRES_NAME=notbank
      - POSTGRES_USER=notbank
      - POSTGRES_PASSWORD=notbank
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - ./backend:/home/user/backend
    depends_on:
      - db
      - redis
      - broker
    security_opt:
      - "apparmor=unconfined"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next
    depends_on:
      - backend
    security_opt:
      - "apparmor=unconfined"
