# Generated by Django 4.0.4 on 2022-05-23 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('currency', models.CharField(max_length=8)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('task_ID', models.CharField(max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Éxito'), (2, 'Error')])),
                ('task_ID', models.CharField(max_length=36)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.balancetransfer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_ID',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_UUID',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='balancetransfer',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_user', to='transactions.user'),
        ),
        migrations.AddField(
            model_name='balancetransfer',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_user', to='transactions.user'),
        ),
    ]
