# Generated by Django 4.0.4 on 2022-05-31 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_firebase_id_user_firebase_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='transactions.transfer'),
        ),
    ]
