# Generated by Django 4.0.4 on 2022-06-07 20:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transferrequest_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('from_currency', models.CharField(max_length=8)),
                ('to_currency', models.CharField(max_length=8)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('fee_amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Éxito'), (1, 'Error'), (2, 'Pendiente')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PendingTransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('task_ID', models.CharField(max_length=300, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Éxito'), (1, 'Error'), (2, 'Pendiente')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
        migrations.DeleteModel(
            name='PendingTransferStatus',
        ),
    ]
