# Generated by Django 4.0.4 on 2022-06-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_rename_user_conversion_from_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversion',
            old_name='from_user',
            new_name='user',
        ),
    ]
