# Generated by Django 4.0.4 on 2022-06-13 15:22

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_rename_from_user_conversion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcuteConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('requestId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('from_currency', models.CharField(max_length=8)),
                ('from_amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('to_currency', models.CharField(max_length=8)),
                ('to_amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('perfect_amount', models.DecimalField(decimal_places=18, max_digits=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('requestId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='conversion',
            name='status',
            field=models.IntegerField(choices=[(0, 'Esperando a balance manager'), (1, 'Error en balance manager'), (2, 'Éxito en balance manager, esperando quote service'), (3, 'Error en quote service'), (4, 'Éxito en quote service')], default=0),
        ),
    ]
