# Generated by Django 4.0.4 on 2022-06-22 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_excuteconversion_pendingconversion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcuteConversion',
            new_name='Quote',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='task_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='task_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
