# Generated by Django 4.0.4 on 2022-06-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_rename_excuteconversion_executeconversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='task_ID',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='task_ID',
            field=models.UUIDField(editable=False),
        ),
    ]
