# Generated by Django 4.0.4 on 2022-06-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_transfer_task_id_alter_transferrequest_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='task_ID',
            field=models.UUIDField(editable=False),
        ),
    ]
