# Generated by Django 4.0.4 on 2022-06-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_conversion_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='status',
            field=models.IntegerField(choices=[(0, 'Esperando a balance manager'), (1, 'Error en balance manager'), (2, 'Éxito en balance manager, esperando quote service'), (3, 'Error en quote service, balance insuficiente'), (4, 'Error en quote service, imposible cumplir'), (5, 'Éxito en quote service')], default=0),
        ),
    ]
