# Generated by Django 4.0.4 on 2022-07-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_conversion_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingTransactionStatus',
            new_name='BMStatusWaitingSyncTask',
        ),
    ]
