# Generated by Django 4.0.4 on 2022-07-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_currenttransfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmstatuswaitingsynctask',
            old_name='task_ID',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='conversion',
            old_name='task_ID',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='currentconversion',
            old_name='requestId',
            new_name='request_id',
        ),
        migrations.RenameField(
            model_name='currenttransfer',
            old_name='task_ID',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='requestId',
            new_name='request_id',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='task_ID',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='transferrequest',
            old_name='task_ID',
            new_name='task_id',
        ),
    ]
