# Generated by Django 4.0.4 on 2022-07-29 03:59

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_rename_task_id_bmstatuswaitingsynctask_task_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('currency', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('fee', models.DecimalField(decimal_places=18, max_digits=36)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
