# Generated by Django 4.0.4 on 2022-05-31 17:35

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('level', models.IntegerField(choices=[(0, 'ERROR'), (1, 'WARNING'), (2, 'INFO'), (3, 'HTTP'), (4, 'DEBUG')])),
                ('service', models.TextField(choices=[('SERVER', 'SERVER'), ('KAFKA_CONSUMER', 'KAFKA CONSUMER'), ('CELERY', 'CELERY')])),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
